name: ldcu
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.19.0
  label_marker: ^1.0.1
  o3d: ^3.1.0
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
