name: ldcu
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  just_audio: ^0.9.36
  o3d: ^3.1.0
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
